/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface CreateTaskBodySchema {
  /**
   * Title of the task
   */
  title: string;
  /**
   * Details of the task
   */
  details: string;
  /**
   * Deadline of the task (Date in string)
   */
  dueDate: string;
  /**
   * Tag(s) of the task
   */
  tags: string[];
  /**
   * Estimated Time to finish the task
   */
  estimatedTime: number;
  [k: string]: unknown;
}
